version: '3'

services:
  pygame-app:
    build: .
    volumes:
      - .:/usr/src/app
    environment:
      - DISPLAY=unix$DISPLAY
      - QT_X11_NO_MITSHM=1
    network_mode: host
    privileged: true
